### ISSUE TITLE
Automatically open Git perspective on start-up

### ISSUE THREAD

**Issue by planger** [eclipsesource/megit#1]
Currently users have to open the Git perspective manually. We should open this by default.

**Comment by jirkafm** [comment]
I found one caveat that `-pluginCustomization plugin_customization.ini` property inside `megit.ini` its path to `plugin_customization.ini` is relative therefore megit should be executed within its directory. 

What works with hypothetical path /usr/local/megit:
```
localhost:~:%
cd /usr/local/megit && ./megit
```

What will be problematic:
```
localhost:~:%
/usr/local/megit/megit
```

Workaround can also be to edit megit.ini and set absolute path `-pluginCustomization <absolute_path>`
