### ISSUE TITLE
Can't start the zip attached to the 0.0.2 release on MacOS

### ISSUE THREAD

**Issue by jmini** [eclipsesource/megit#10]
Go to the [0.0.2 (2020-12)](https://github.com/eclipsesource/megit/releases/tag/v0.0.2) page.

I have downloaded the `com.eclipsesource.megit-macosx.cocoa.x86_64.zip` ([link](https://github.com/eclipsesource/megit/releases/download/v0.0.2/com.eclipsesource.megit-macosx.cocoa.x86_64.zip))

I have unzipped the file (standard macOS utility)
I get this error dialog when I start the decompressed "Eclipse.app" file:

<img width="532" alt="Error dialog: Eclipse is damaged and can't be opened. You should move it to the Bin." src="https://user-images.githubusercontent.com/1222165/108417935-e02d6480-7230-11eb-8b9c-fbda1f0d5319.png">

**Comment by planger** [comment]
I've never tested the MacOS build (I don't have one) and I'm not sure what's wrong, unfortunately. :/

**Comment by jmini** [comment]
The local build is working:

With Java 11 on the path:
```
$ java -version
openjdk version "11.0.5" 2019-10-15
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.5+10)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.5+10, mixed mode)
```

I can run:
```
mvn verify -f com.eclipsesource.megit.parent/pom.xml
```

And open the generated `Eclipse.app`.

1) Either unzip:
```
com.eclipsesource.megit.product/target/products/com.eclipsesource.megit-macosx.cocoa.x86_64.zip
```
and start the `Eclipse.app` extracted from the zip.

2) Or start:
```
com.eclipsesource.megit.product/target/products/com.eclipsesource.megit/macosx/cocoa/x86_64/Eclipse.app
```

**Comment by jmini** [comment]
----

One note that you need to know (standard for all RCP app including Eclipse IDE itself):

You should have Java 11 which is not the default on my mac.

Either you start with `open <path to Eclipse.app>` from a Terminal where Java 11 is the default version.

Or you edit the file `megit.ini` (inside `Eclipse.app` with right click "Show Package Contents" and edit the file `Eclipse.app/Contents/Eclipse/megit.ini`) to add the `-vm` entry with the path pointing to your Java 11 installation.
See https://wiki.eclipse.org/Eclipse.ini

**Comment by jirkafm** [comment]
I also cannot test it on MacOS (running on Linux). 

Could you please compare the content of downloaded `Eclipse.app` and an `Eclipse.app` from a build? I'd say that if both of them can be executed from terminal with proper java then we are somehow OK. If the downloaded `Eclipse.app` cannot be run  that would mean that the package is corrupted. 

Thanks for your input at least we have some suggestion how to run it on MacOS alternatively.

**Comment by cristian-anita** [comment]
Workaround (tested on macOS Big Sur):
> sudo xattr -rd com.apple.quarantine ./Eclipse.app

**Comment by planger** [comment]
See also https://bugs.eclipse.org/bugs/show_bug.cgi?id=398450
