### ISSUE TITLE
Long-term switching to a branch

### ISSUE THREAD

**Issue by ghostaz** [eclipsesource/megit#18]
Hi, switching branches can take 10 minutes. There are about 15 thousand files in the repository, but another client (Git Extensions) does it faster than a minute. How can I speed up the process?

**Comment by planger** [comment]
Thanks for the feedback! Maybe it helps increasing the Window Cache limit in Preferences -> Team -> Git?
As this is likely an EGit or JGit issue, I would recommend opening an issue in those projects directly via https://bugs.eclipse.org/bugs/enter_bug.cgi?product=JGit or https://bugs.eclipse.org/bugs/enter_bug.cgi?product=EGit

**Comment by planger** [comment]
I'm closing this issue, as this is an upstream topic.
