### ISSUE TITLE
LookAndFeel change

### ISSUE THREAD

**Issue by Kermel** [eclipsesource/megit#21]
Hello, is it possile to anyhow change the look and feel for MeGit? The default black theme really hurt my eyes so it would be nice to have the possibility to change :-(

**Comment by Kermel** [comment]
NVM, I'm just blind, found it :)

**Comment by planger** [comment]
Thanks for your feedback! Any Eclipse theme will work, see e.g. https://www.tabnine.com/blog/top-eclipse-ide-themes/
