### ISSUE TITLE
Build for Mac os Arm 64

### ISSUE THREAD

**Issue by hocesjc** [eclipsesource/megit#27]
Please also build for Mac os Arm 64 (supported by Eclipse).

**Comment by hocesjc** [comment]
Its work with add
`	<environment>
							<os>macosx</os>
							<ws>cocoa</ws>
							<arch>aarch64</arch>
						</environment>`	
in com.eclipsesource.megit.parent/pom.xml

**Comment by planger** [comment]
Sure, I'm happy to add it if you confirm it works.
Can you please open a PR and test whether the result works for you after a local build? I have no machine to test Mac support. Thanks!
