### ISSUE TITLE
How to revert back "Install New Software" ?

### ISSUE THREAD

**Issue by ocoka** [eclipsesource/megit#30]
I understand the intent of the project to make it into a separate product, it's very cool, but how to return the ability to install third-party plugins ? I want to edit some files with specific editors while in merge mode for example, as I understand Eclipse platform it's just a configuration moment, but I don't know there it is ? Maybe you can point me ? Or maybe you can add special option for people who want s such thing ?

**Comment by planger** [comment]
I'm afraid you can't without rebuilding megit, as it doesn't include the required infrastructure to add new P2 repositories to install additional software. Of course you could add additional features into the [product definition](https://github.com/eclipsesource/megit/blob/master/com.eclipsesource.megit.product/megit.product#L314) and rebuild though.
