### ISSUE TITLE
Fail to build Megit on Linux

### ISSUE THREAD

**Issue by spaceKelan** [eclipsesource/megit#34]
Hi there 👋🏼 ,

I am on `CentOS7` and I tried this:

I installed Java 17
and maven (3.0.5) via 
```bash
sudo yum install <maven>
```
When I try to build via
```bash
mvn clean install
```

I get the following error:
![image](https://github.com/eclipsesource/megit/assets/51329415/d71e6a35-14d2-43d8-8e1f-a620cce7beeb)

So I tried to install maven 3.9.4 with `wget`.

Then I got the following error:
```
Caused by: java.lang.UnsupportedClassVersionError: org/eclipse/tycho/core/maven/TychoMavenLifecycleParticipant 
has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the 
Java Runtime only recognizes class file versions up to 52.0
```
Therefore, I tried to figure out which Java to install and according to [stackoverflow](https://stackoverflow.com/questions/10382929/how-to-fix-java-lang-unsupportedclassversionerror-unsupported-major-minor-versi)
I need this `Java SE 8 = 52` - which is lower than the minimum Java you need.

Before it gets really wild, **which maven would I need at least**?

Please help.

**Comment by planger** [comment]
Hi @spaceKelan,
I'm on Ubuntu 22.04.2 and use maven 3.9.2 and Java Temurin-17.0.8+7.
Maven however by default takes the Java version that is referenced from the environment variable `$JAVA_HOME`. So maybe in your case this environment variable points to an old Java?

**Comment by spaceKelan** [comment]
hi  @planger - thanks for your response!

that sounds reasonable and it resolved the issue!

I went for 
```bash
java -version // would print 17...
which java
``` 
traced the symlink to set in `/etc/profile.d/maven.sh` as described [here](https://linuxize.com/post/how-to-install-apache-maven-on-centos-7/) (but with `wget https://dlcdn.apache.org/maven/maven-3/3.9.4/binaries/apache-maven-3.9.4-bin.tar.gz -P /tmp`)
```maven.sh
$JAVA_HOME=/usr/lib/jvm/jdk-17-oracle-x64/
``` 
After sourcing it I ran `mvn clean install` again and got a `BUILD_SUCCESS`
![image](https://github.com/eclipsesource/megit/assets/51329415/082c870c-7957-4ca9-aab9-7ee2329bb75d)

**Comment by spaceKelan** [comment]
@planger even though I built it successfully I receive this error message when trying to run 
```bash
megit
``` 
``` 
bash: megit: command not found
```

**Comment by planger** [comment]
I'm glad I could help resolving your build issue.
The build command above just builds it, but doesn't install it in your system. The "binaries" end up in `megit/com.eclipsesource.megit.product/target/products/com.eclipsesource.megit`. There should be a folder for your architecture with an executable called `megit` in it and that should be runnable.

If you want to install that on your system, you'd have to put this folder that contains the executable in your path.

Please note that you could also just download from [the releases](https://github.com/eclipsesource/megit/releases) to get the same thing as in the `target/products` folder without having to build locally.
