### ISSUE TITLE
New install ubuntu 22.04 Megit throws error

### ISSUE THREAD

**Issue by rogercreagh** [eclipsesource/megit#36]
Instructions as per readme - download release file, unzip it (to a new folder for it) and run megit.

Popup - `Megit. An error has occurred. See the log file...`

Log file ends with
```
!ENTRY org.eclipse.e4.ui.dialogs 2 0 2023-09-27 16:24:39.195
!MESSAGE Could not resolve module: org.eclipse.e4.ui.dialogs [80]
  Unresolved requirement: Require-Bundle: org.eclipse.jface; bundle-version="3.11.0"
    -> Bundle-SymbolicName: org.eclipse.jface; bundle-version="3.30.0.v20230509-0720"; singleton:="true"
       org.eclipse.jface [138]
         Unresolved requirement: Require-Bundle: org.eclipse.swt; bundle-version="[3.111.0,4.0.0)"; visibility:="reexport"
           -> Bundle-SymbolicName: org.eclipse.swt; bundle-version="3.124.0.v20230523-1044"; singleton:="true"
              org.eclipse.swt [158]
                Unresolved requirement: Require-Capability: osgi.ee; filter:="(&(osgi.ee=JavaSE)(version=17))"


!ENTRY org.eclipse.osgi 4 0 2023-09-27 16:24:39.196
!MESSAGE Application error
!STACK 1
java.lang.IllegalStateException: Unable to acquire application service. Ensure that the org.eclipse.core.runtime bundle is resolved and started (see config.ini).
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:81)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:402)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1467)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1440)
```
There were a whole load of `could not resolve module`sections before that.
config.ini contains:
```
#This configuration file was written by: org.eclipse.equinox.internal.frameworkadmin.equinox.EquinoxFwConfigFileParser
#Thu Jul 13 22:42:09 CEST 2023
eclipse.product=com.eclipsesource.megit.plugin.megit
org.eclipse.equinox.simpleconfigurator.configUrl=file\:org.eclipse.equinox.simpleconfigurator/bundles.info
osgi.bundles.defaultStartLevel=4
eclipse.application=org.eclipse.ui.ide.workbench
osgi.bundles=reference\:file\:org.eclipse.equinox.simpleconfigurator_1.4.200.v20221111-1340.jar@1\:start
eclipse.p2.data.area=@config.dir/../p2
eclipse.p2.profile=DefaultProfile
osgi.framework=file\:plugins/org.eclipse.osgi_3.18.400.v20230509-2241.jar
osgi.framework.extensions=reference\:file\:org.eclipse.osgi.compatibility.state_1.2.800.v20221116-1440.jar
```
Java version is openjdk 11.0.20.1

What is missing? Help needed please.

**Comment by planger** [comment]
I think, you get errors because of your Java version. Megit requires [Java 17 or higher](https://github.com/eclipsesource/megit#installing-megit).

**Comment by rogercreagh** [comment]
Doh! I read it as Java 7 or higher and thought I was ok with 11 !

**Comment by planger** [comment]
Let me know if it works with Java 17!

**Comment by rogercreagh** [comment]
@planger Yep, simply updateing java sdk to 17.0.8.1 and it works fine. 

Its a bit confusing cos Megit uses the Eclipse egit help texts which are themselves out of date and refer to menu options that have moved or changed. Maybe one day someone will sort out the help files. In the meantime I am struggling to do a first commit and push  which doesn't seem to be working - presumably I've not set something right as nothing happens when I press the button but its not telling me what. I'll get there.

I also need to remember why I was stuck on JDK11 - there was some previous compatibility issue with some software that required v11 - I guess I'll find what is broken eventually!

**Comment by planger** [comment]
Ok, thanks! Yes, that's probably right. The documentation doesn't expect the slim-down that Megit does. You can use Ctrl+3 to open quick find and with that you should be able to open almost any of the hidden menus, such as preferences, etc. Hopefully with those you'll find what you are looking for.

I can also recommend https://wiki.eclipse.org/EGit/User_Guide which has been written for EGit but applies to Megit to a very large degree. Good luck!
