### ISSUE TITLE
Install new Software not appearing in the Help menu

### ISSUE THREAD

**Issue by ShaiNata** [eclipsesource/megit#37]
"Install new Software" option from the help menu is missing.
There is no option to install the Java implementation of Git - optional LFS support plugin.

**Comment by planger** [comment]
Thanks for the feedback! Good idea, I created a PR to add Git LFS support. For me it works now to activate Git LFS support via the preferences. Do you want to test first (building locally and testing whether it works for you)? Otherwise, I'd just merge it and publish this with the next release.

**Comment by planger** [comment]
Published with [0.5.0](https://github.com/eclipsesource/megit/releases/tag/v0.5.0)
