### ISSUE TITLE
Build fails

### ISSUE THREAD

**Issue by jonek** [eclipsesource/megit#4]
Steps to reproduce:
- clone repo
- `cd com.eclipsesource.megit.parent`
- `mvn clean install`

results in:

`[ERROR] Failed to resolve target definition /home/jeick/projects/megit/com.eclipsesource.megit.target/com.eclipsesource.megit.target.target: Could not find "org.eclipse.jgit.feature.group/5.1.0.201809111528-r" in the repositories of the current location -> [Help 1]`

**Comment by planger** [comment]
Thanks, fixed with https://github.com/eclipsesource/megit/commit/8183bc3d38af144fcc037c25b720e1afc95c3227
