### ISSUE TITLE
Add the Java version to the configuration file

### ISSUE THREAD

**Issue by agamez73** [eclipsesource/megit#41]
It is possible to specify in the configuration file "megit.ini" or in another configuration file the required java version.
For when there is more than one version of java installed on your computer.

## Example of default location for JDK or JRE:
jdkhome="/opt/oracle/java/jdk/17"

Thanks
:)

**Comment by planger** [comment]
Yes, you should be able to specify the JDK/JRE in the `megit.ini`:

```
-startup
plugins/org.eclipse.equinox.launcher_1.6.500.v20230717-2134.jar
--launcher.library
plugins/org.eclipse.equinox.launcher.gtk.linux.x86_64_1.2.700.v20221108-1024
-pluginCustomization
plugin_customization.ini
-cssTheme
org.eclipse.e4.ui.css.theme.e4_dark
-vm
<path-to-vm>
```

For more info, see the [docs on the launcher ini](https://help.eclipse.org/latest/index.jsp?topic=%2Forg.eclipse.platform.doc.isv%2Freference%2Fmisc%2Flauncher_ini.html) and the [Eclipse wiki on that topic](https://wiki.eclipse.org/Eclipse.ini#Specifying_the_JVM).

**Comment by titou10titou10** [comment]
@planger megit could be bundled with the correct JRE, so you can control the version at development/build time and you eliminate the need for users to install/configure a JRE on the side
WDYT?

**Comment by planger** [comment]
@titou10titou10 Thank you very much for your suggestion and especially the PR! I'm in favor of including the VM. It'll sure simplify the installation. I'll check your PR soon, but I'm out of office in the next weeks, so it may take a while, but I'll get back to it.

Thanks again!

**Comment by agamez73** [comment]
Thank you very much
