### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by Simorenarium** [eclipsesource/megit#5]
Hi, I'm having a build error because certain dependencies can not be downloaded.
Also, as a Request, could you provide Releases and Downloads here on github?
[build.log](https://github.com/eclipsesource/megit/files/5464648/build.log)

**Comment by planger** [comment]
Thanks to @jirkafm the build works fine now (https://github.com/eclipsesource/megit/pull/6).
Also I've uploaded the built products for Linux, Windows and MacOS as a release:
https://github.com/eclipsesource/megit/releases/tag/v0.0.1
