### ISSUE TITLE
There is no possible to assign a shortcut for compare command in HISTORY view

### ISSUE THREAD

**Issue by Golyshkin** [eclipsesource/megit#52]
There is no possible to assign a shortcut for compare command in HISTORY view. The details see below picture:

![image](https://github.com/eclipsesource/megit/assets/772340/ff47beb0-61c2-48ab-b86f-838e1967401b)

Used configuration: 
`
com.eclipsesource.megit.plugin, Version: 0.6.0.20240201-2049, Location: reference:file:plugins/com.eclipsesource.megit.plugin_0.6.0.20240201-2049.jar
`

**Comment by planger** [comment]
Thank you for raising this issue. I think it should be possible to do that though.

1. Type Ctrl-3 to open "Find Actions"
2. Search keyboard preferences: e.g. type "pref key"
3. Find the command you want to assign a keybinding for:

![image](https://github.com/eclipsesource/megit/assets/588090/00954cea-2a3d-4580-a84f-2d6fe44b4c23)

Please re-open if there is some follow up question! Thank you!

**Comment by Golyshkin** [comment]
My current settings are showed on picture below and it doesn't work at all for mentioned in issue screen
![image](https://github.com/eclipsesource/megit/assets/772340/75a1cad6-05ad-47d7-85c7-fd5ec9a115d7)

Could u provide more info how to proper configure it?

**Comment by planger** [comment]
Hm, I'm afraid you are right. For some reason, the keyboard shortcut assigned doesn't work from the History view. I think assigning a keyboard shortcut to this action only works for the file navigator.

However, hitting `Enter` works.

**Comment by Golyshkin** [comment]
No it doesn't and just open the file. Is it possible to fix an issue with shortcuts?

**Comment by planger** [comment]
This issue would need to be fixed in [EGit](https://github.com/eclipse-egit/egit) directly. So it is probably best to open the issue there.

**Comment by Golyshkin** [comment]
https://github.com/eclipse-egit/egit/issues/25 - DONE
