### ISSUE TITLE
Update megit, so that syntax highlighting in egit's compare editor is possible out of the box

### ISSUE THREAD

**Issue by systemoperator** [eclipsesource/megit#55]
Update megit, so that syntax highlighting in egit's compare editor is possible out of the box, according to https://github.com/eclipse-egit/egit/issues/41.

**Comment by planger** [comment]
Good idea, I've upgraded and added tm4e. A new release for 2024-06 is available:
https://github.com/eclipsesource/megit/releases/tag/v0.7.0

Please let me know if you run into any issues.

**Comment by systemoperator** [comment]
Works great so far. :)
