### ISSUE TITLE
New eGit release available

### ISSUE THREAD

**Issue by Golyshkin** [eclipsesource/megit#58]
There is https://github.com/eclipse-egit/egit/releases/tag/v7.0.0.202408202050-m3 available. Are u planning to update a MeGit accordingly?

**Comment by planger** [comment]
We usually provide a new MeGit release every six months with the latest EGit release, unless there is a specific reason to do additional releases.
Do you think there is a specific reason for the latest EGit release?

**Comment by Golyshkin** [comment]
six months already gone...

**Comment by planger** [comment]
> six month is gone :-) Waiting for new Rel

The last release was in 2025-06. See https://github.com/eclipsesource/megit/releases
The next one is scheduled based on the December releases of Eclipse
